apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: combine-social
  name: timeline-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline-api
  template:
    metadata:
      labels:
        app: timeline-api
    spec:
      containers:
      - name: api
        image: ghcr.io/combine-social/timeline-api:1.1.1
        resources:
          requests:
            memory: "256Mi"
        env:
        - name: WEBSITE
          value: {{ .Values.website }}
        - name: CLIENT_NAME
          value: combine.social
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: timeline-secret
              key: dburl
---
apiVersion: v1
kind: Service
metadata:
  name: timeline-api
  namespace: combine-social
spec:
  type: ClusterIP
  ports:
  - name: timeline-api
    port: 3000
    targetPort: 3000
  selector:
    app: timeline-api
