apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeline-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: timeline-tls

  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: timeline-api
            port:
              number: 3000
      - path: /api/v1/actor
        pathType: Prefix
        backend:
          service:
            name: timeline-actor
            port:
              number: 3001
      - path: /.well-known/webfinger
        pathType: Prefix
        backend:
          service:
            name: timeline-actor
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: timeline-web
            port:
              number: 3000
