apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: combine-social
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11.10-alpine
        resources:
          requests:
            memory: "256Mi"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: timeline-secret
              key: rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: timeline-secret
              key: rabbitmq-pass
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: combine-social
spec:
  type: ClusterIP
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
