apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: combine-social
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server"]
        args: ["--save", "60", "1", "--loglevel", "notice"]
        resources:
          requests:
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mastodon
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
