apiVersion: v1
kind: Secret
metadata:
  namespace: combine-social
  name: timeline-secret
stringData:
  dburl: postgres://username:secret@10.0.18.51/combinesocial
  rabbitmq-url: amqp://username:secret@rabbitmq
  rabbitmq-user: username
  rabbitmq-pass: secret
---
apiVersion: v1
data:
  pubkey.pem: <base64 encoded public key>
kind: Secret
metadata:
  name: pubkey-actor-secret
  namespace: combine-social
---
apiVersion: v1
data:
  privkey.pem: <base64 encoded private key>
kind: Secret
metadata:
  name: privkey-actor-secret
  namespace: combine-social
