apiVersion: v1
kind: Secret
metadata:
  namespace: combine-social
  name: timeline-secret
stringData:
  dburl: postgres://username:secret@10.0.18.51/combinesocial
  rabbitmq-url: amqp://username:secret@rabbitmq
  rabbitmq-user: username
  rabbitmq-pass: secret
